compressionLevel: mixed

httpProxy: "http://1.1.1.1:8080"

httpsProxy: "http://1.1.1.1:8080"

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1108110
  - 1108111

npmPublishRegistry: "https://nexus.protontech.ch/repository/web-npm/"

npmScopes:
  proton-meet:
    npmRegistryServer: "https://nexus.protontech.ch/repository/meet-npm/"
  tpe:
    npmAuthToken: "${CI_JOB_TOKEN:-}"
    npmRegistryServer: "https://gitlab.protontech.ch/api/v4/projects/4357/packages/npm/"

plugins:
  - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.12.0.cjs
